-- MySQL Script generated by MySQL Workbench
-- Sun Jul 12 01:10:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema facflowDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facflowDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS facflowDB;

CREATE SCHEMA IF NOT EXISTS `facflowDB` DEFAULT CHARACTER SET utf8 ;
USE `facflowDB` ;

-- -----------------------------------------------------
-- Table `facflowDB`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facflowDB`.`Product` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `productCode` VARCHAR(45) NOT NULL,
  `productName` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`productId`),
  UNIQUE INDEX `productCode_UNIQUE` (`productCode` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facflowDB`.`ProductPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facflowDB`.`ProductPlan` (
  `planId` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NOT NULL,
  `planDate` DATE NOT NULL,
  `dueDate` DATE NOT NULL,
  `targetQty` INT NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'WAIT',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`planId`),
  INDEX `fk_Plan_Product_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_Plan_Product`
    FOREIGN KEY (`productId`)
    REFERENCES `facflowDB`.`Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facflowDB`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facflowDB`.`Equipment` (
  `equipmentId` INT NOT NULL AUTO_INCREMENT,
  `equipmentName` VARCHAR(45) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'IDLE',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`equipmentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facflowDB`.`Production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facflowDB`.`Production` (
  `productionId` INT NOT NULL AUTO_INCREMENT,
  `planId` INT NOT NULL,
  `equipmentId` INT NOT NULL,
  `startTime` TIMESTAMP NULL,
  `endTime` TIMESTAMP NULL,
  `goodQty` INT NOT NULL DEFAULT 0,
  `defectQty` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`productionId`),
  INDEX `fk_Production_Plan1_idx` (`planId` ASC) VISIBLE,
  INDEX `fk_Production_Equipment1_idx` (`equipmentId` ASC) VISIBLE,
  CONSTRAINT `fk_Production_Plan1`
    FOREIGN KEY (`planId`)
    REFERENCES `facflowDB`.`ProductPlan` (`planId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Production_Equipment1`
    FOREIGN KEY (`equipmentId`)
    REFERENCES `facflowDB`.`Equipment` (`equipmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facflowDB`.`Defect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facflowDB`.`Defect` (
  `defectId` INT NOT NULL AUTO_INCREMENT,
  `productionId` INT NOT NULL,
  `defectType` VARCHAR(45) NULL,
  `qty` INT NOT NULL,
  PRIMARY KEY (`defectId`),
  INDEX `fk_Defect_Production1_idx` (`productionId` ASC) VISIBLE,
  CONSTRAINT `fk_Defect_Production1`
    FOREIGN KEY (`productionId`)
    REFERENCES `facflowDB`.`Production` (`productionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `facflowDB`.`EquipmentProduct`
-- -----------------------------------------------------
create table if not exists `facflowDB`.`EquipmentProduct` (
	`equipmentProductId` INT NOT NULL AUTO_INCREMENT,
	`equipmentId` int not null,
    `productId` int not null,
    `hourlyCapacity` int,
    primary key(`equipmentProductId`),
    
    CONSTRAINT `uk_equipment_product`
        UNIQUE (`equipmentId`, `productId`),
    
    CONSTRAINT `fk_equipment_product_equipment`
	FOREIGN KEY (`equipmentId`)
		references `facflowDB`.`Equipment` (`equipmentId`)
        ON DELETE NO ACTION
		ON UPDATE NO ACTION,
        
	CONSTRAINT `fk_equipment_product_product`
	FOREIGN KEY (`productId`)
		references `facflowDB`.`Product` (`productId`)
        ON DELETE NO ACTION
		ON UPDATE NO ACTION
);








SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
